SomeCreativeName_FoodDeliveryComp/SomeCreativeName_FoodDeliveryComp/Controllers/ShoppingCartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using SomeCreativeName_FoodDeliveryComp.Areas.Identity.Data;
using SomeCreativeName_FoodDeliveryComp.DAL;
using SomeCreativeName_FoodDeliveryComp.DAL.DataModels;
using SomeCreativeName_FoodDeliveryComp.Helpers;
using SomeCreativeName_FoodDeliveryComp.Models;

namespace SomeCreativeName_FoodDeliveryComp.Controllers
{
    public class ShoppingCartItemsController : Controller
    {
        private readonly CompanyContext context;
        private readonly IHtmlLocalizer<ShoppingCartItemsController> localizer;

        public ShoppingCartItemsController(CompanyContext _context, IHtmlLocalizer<ShoppingCartItemsController> _localizer)
        {
            context = _context;
            localizer = _localizer;
        }

        [HttpGet]
        public IActionResult AddToCart(MenuItem menuItem, int qtty)
        {
            SessionObjectNullCheck("cart");

            var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItemViewModel>>(HttpContext.Session, "cart");

            CartRepository.AddToCart(cart, menuItem, qtty);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Index()
        {
            SessionObjectNullCheck("cart");
            var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItemViewModel>>(HttpContext.Session, "cart");
            return View(CartRepository.GetAll(cart));
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = CartRepository.DeleteFromCart(SessionHelper.GetObjectFromJson<List<ShoppingCartItemViewModel>>(HttpContext.Session, "cart"), (int)id);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            

            return RedirectToAction(nameof(Index));
        }

        public IActionResult EmptyCart()
        {

            CartRepository.EmptyCart(SessionHelper.GetObjectFromJson<List<ShoppingCartItemViewModel>>(HttpContext.Session, "cart"));
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", new List<ShoppingCartItemViewModel>());
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public IActionResult PlaceOrder()
        {
            SessionObjectNullCheck("cart");
            var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItemViewModel>>(HttpContext.Session, "cart");
            if (cart.Count <= 0)
            {
                return RedirectToAction(nameof(Index));
            }

            context.Orders.Add(new Order()
            {
                Costumer = context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name) as Costumer,
                //OrderItemsId = new List<OrderItem>()
            });
            context.SaveChanges();

            var order = new List<OrderItem>();
            foreach (var item in cart)
            {
                context.MenuItems.Update(context.MenuItems.SingleOrDefault(menuitem => menuitem == item.MenuItem));
                order.Add(new OrderItem()
                {
                    MenuItemId = item.MenuItem,
                    Quantity = item.Quantity,
                    Order = context.Orders.Last()
                });

                if (item.MenuItem.OrderCount != null)
                    context.MenuItems.SingleOrDefault(menuitem => menuitem == item.MenuItem).OrderCount += item.Quantity;
                else
                    context.MenuItems.SingleOrDefault(menuitem => menuitem == item.MenuItem).OrderCount = item.Quantity;
            }
            context.Orders.Last().OrderItemsId = order;
            context.SaveChanges();
            EmptyCart();
            //var orderitemsTmp = context.OrderItems.ToList();
            //var orderitems = orderitemsTmp.TakeLast(cart.Count).ToList();

            //context.Orders.Update(context.Orders.Last());
            //context.Orders.Last().OrderItemsId = orderitems;
            context.SaveChanges();
            return RedirectToAction(nameof(Index));


        }


        private void SessionObjectNullCheck(string key)
        {
            var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItemViewModel>>(HttpContext.Session, key);
            if (cart == null)
            {
                cart = new List<ShoppingCartItemViewModel>();
                SessionHelper.SetObjectAsJson(HttpContext.Session, key, cart);
            }
        }
    }
}

SomeCreativeName_FoodDeliveryComp/SomeCreativeName_FoodDeliveryComp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using SomeCreativeName_FoodDeliveryComp.Helpers

@inject IHtmlLocalizer<SharedResourceHelper> Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SomeCreativeName_FoodDeliveryComp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/banner_image.jpg" class="top img-responsive" /></a>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SomeCreativeName_FoodDeliveryComp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">@Localizer["About"]</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">@Localizer["Contact"]</a></li>
                    <li><a asp-area="" asp-controller="ShoppingCartItems" asp-action="Index">@Localizer["Shopping Cart"]</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    @RenderBody()

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>